#!/bin/sh
jasmine

git diff --cached --name-only --diff-filter=AMR \
| grep -v '^public/' \
| grep '.js' \
| xargs -r js-beautify -r -n -a -j -s 2 --good-stuff

git diff --cached --name-only --diff-filter=AMR \
| xargs -r git add
